### ISSUE TITLE
Instrukce

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#10]
Vytvořit třídu s instrukcemi

**Comment by Kossyr** [comment]
A jejich kody

**Comment by Kossyr** [comment]
hotovo s 64f9b6a665eda566f924e348f4e75741b324dcfb

**Comment by SmausJakub** [comment]
Otvírám, protože není hotovo. Je třeba dostudovat nové instrukce a ověřit funkčnost. Souvisí s #16 #15

**Comment by Kossyr** [comment]
K real instrukcím
LRT bude načítat real číslo do stacku ?
OPF budeme používat místo OPR když jsou tam real čísla ?
Co uděláme s načítáním a ukládáním real čísel, tedy instrukce LOD a STO ?

#31 #30 #29

**Comment by SmausJakub** [comment]
Přesně tak. LRT bude namísto zabrání dvou míst ve stacku zabírat jedno místo a to pomocí převodu díky těmto metodám z Floatu. 
Float.intBitsToFloat
Float.floatToRawIntBits
Ano, já bych to tak viděl, OPF operace budou pracovat s celými čísly a OPR s čísly reálnými.

Pro načítání a ukládání jsou vytvořené nové instrukce a to LOR a STR. Principiálně fungují stejně, jen pracují s reálnými čísly.

**Comment by SmausJakub** [comment]
Tímto by mělo bejt toto issue splněno 2ba10da9ac12b147f1d930ac440d0d0803e02e7d
