### ISSUE TITLE
JUnit testy

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#11]
Budou třeba

**Comment by SmausJakub** [comment]
Nejprve je nutné začít s nejvíce zatěžovanou a nejdůležitější funkcionalitou překladače.

**Comment by Kossyr** [comment]
Jen jsem řekl že budou třeba někdy v dohledné době

**Comment by Kossyr** [comment]
Taky se o nich píše na courseware myslím

**Comment by Kossyr** [comment]
A je to dobrá kultura je dělat

**Comment by Kossyr** [comment]
Dump, už to začíná něco dělat, takže je třeba to testovat!

**Comment by Kossyr** [comment]
Určitě bychom mohli využít naše testovací soubory a v JUnit je načíst, poslat do programu a připravit si v souboru, jak by ty instrukce měly vypadat ?

**Comment by SmausJakub** [comment]
Souhlasím, dobrý nápad. Podívám se na to blíže.

**Comment by Kossyr** [comment]
Silně souvisí s #27

**Comment by Kossyr** [comment]
Určitě by měly být:
testy pro překladač
testy pro interpret
složitější testy pro oba ? (tedy zdroják do překladače, výstup do interpretu, zkontrolovat výstup ?)

potom by to mohlo být, že testy pro jednotlivé části budou zaměřený na nějakou konkrétní věc
ty složitější testy by byly více produkčního rázu, něco jako "skutečné" programy

**Comment by Kossyr** [comment]
Přijde mi, že dělat testy jen pro překladač nebude nejvhodnější. Není to s čím zkontrolovat. Je možno nechat si program přeložit a pak to srovnávat s těmi instrukcemi, ale srovnávat výtvor překladače s jiným výtvorem toho samého překladače je trochu divné.

Přemýšlím, že u deklarací by šlo kontrolovat tabulku symbolů, i když tam by se dalo zkontrolovat jen to, jestli byly deklarovány.

Takže spíš myslím, že by ty testy měly být rovnou s interpretem

**Comment by SmausJakub** [comment]
To je pravda, asi to bude chtít komplexní projetí celého programu

**Comment by Kossyr** [comment]
To mi zase přijde jako overkill 🥇

**Comment by Kossyr** [comment]
Ty komplexní jsou složitý a přináší více práce než užitku. Interpret můžeš odzkoušet pomocí instrukcí a zkontrolování zásobníku, to by neměl být problém. Kompiler bych vyzkoušel chybový výstupy na chybový vstupy a pak jen zkontrolovat, že na správný vstupy je výstup 0. Kontrola těch instrukcí je celkem složitý problém, nepřijde mi to chytrý srovnávat výstup kompileru s předešlým výstupem kompileru ... to by bylo velké překvapení, kdyby to neprošlo. To radši bych jen zkontroloval, že to nějak přeložil a jak to už je záležitost dalších entit.

**Comment by Kossyr** [comment]
nástřel 22b8cee239f425fb973005bd45ad1be51bd6fdb7

**Comment by Kossyr** [comment]
Mslím, že co šlo, jsme udělali. Teď už je to v jiných rukách
