### ISSUE TITLE
Visitory

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#13]
Vytvořit visitory pro jednotlivé části stromu.

- [x] Visitor pro expressiony

- [x] Visitor pro atomy

- [x] Visitor pro deklarace

- [x] Visitor pro block

- [x] Visitor pro program

- [x] Visitor pro statementy

**Comment by Kossyr** [comment]
- [ ] Visitor pro expressiony

- [ ] Visitor pro atomy

- [ ] Visitor pro deklarace

- [ ] Visitor pro block

- [ ] Visitor pro program

- [ ] Visitor pro statementy

**Comment by SmausJakub** [comment]
Přidán visitor pro deklarace a block 5a0b8123f17dd653ab561cc983255707f5cecb76

**Comment by Kossyr** [comment]
opraveno 5a0b812a hotovo s 25a46eaba049b52f198086adc87b5244e1a01009
