### ISSUE TITLE
Reprezentace typů

### ISSUE THREAD

**Issue by SmausJakub** [SmausJakub/heine-fluch#15]
Vyřešit, jak budou reprezentovány typy

- [x] číslo

- [ ] řetězec

- [x] reálné číslo

- [x] bool

**Comment by Kossyr** [comment]
Závisí na nich #20 #2
mělo by být prioritou

**Comment by Kossyr** [comment]
číslo - int číslo
bool - 0 a 1 (false a true)

real - ??
string - ??

**Comment by Kossyr** [comment]
#30 #29

**Comment by SmausJakub** [comment]
Real bych viděl na float, kde bychom pomocí metod 
Float.intBitsToFloat
Float.floatToRawIntBits
nastavovali příslušné desetinná čísla, jako integery.
Čili naše reálná čísla = int + příslušné metody

**Comment by Kossyr** [comment]
String odročen
