### ISSUE TITLE
Vytvořit Překladač

### ISSUE THREAD

**Issue by SmausJakub** [SmausJakub/heine-fluch#18]
Třída Compiler.

Přeloží zadaný soubor do instrukcí jazyka PL/0.

Bude využívat instrukce #10 #16 a visitory #13

**Comment by Kossyr** [comment]
Visitory hotovy s 25a46eaba049b52f198086adc87b5244e1a01009

Nyní program prochází strom a vytváří všechny požadované třídy.

Nyní stačí projít tyto třídy a za pomoci tabulky symbolů udělat instrukce

**Comment by Kossyr** [comment]
10e168c830eb2acde6796563ae6e8a5952a779a4
Dodělání Compiler tříd dokončí překladač
compiler #20

**Comment by Kossyr** [comment]
větší změna s df46dad888ccb5bcbc34fd0dd7680829fa690cf6
překladač nyní podporuje tři mody

- legacy - pl/0 (var, nejsou not, and or)

- default - defaultní nastavení, implicitní přetypování

- strict - kontrola typů, není možno přetypovat

**Comment by Kossyr** [comment]
7fcd758ccf37b52dd7b930a2ab82582fc711dfa9
Zbývá otestovat.
