### ISSUE TITLE
Řádně otestovat a doopravit interpret

### ISSUE THREAD

**Issue by SmausJakub** [SmausJakub/heine-fluch#19]
Vyzkoušet co možná nejvíc různých testovacích souborů s instrukcemi a jejich průběh vykonání porovnávat s online debuggerem.

**Comment by Kossyr** [comment]
nelze přeložit kvůli chybě v Interpreter.java

**Comment by Kossyr** [comment]
planý poplach, chyba na mé straně

**Comment by Kossyr** [comment]
to co tam je by mělo fungovat, pojďme to rozšířit
