### ISSUE TITLE
Vlastní interpret

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#2]
Info: Vlastní interpret (řádkový, bez rozhraní, složitý alespoň jako rozšířená PL/0) je za 6 bodů. 

Chtělo by to se alespoň zamyslet, že bychom to udělali.

**Comment by Kossyr** [comment]
Řádkový. Bude využívat instructionHandler pro parse načtených instrukcí. Bude využívat stack (řekl bych implementace polem). Vykoná zadné instrukce (styl PL0).

**Comment by Kossyr** [comment]
Pozor na rozšířené instrukce, nikde jsem zatím k nim nenašel dokumentaci.

Zatím bych se soustředil, aby zvládl základní instrukce. Referenčně by měl dát všechny příklady instrukcí uvedených na courseware.

**Comment by SmausJakub** [comment]
Rozumím.

**Comment by SmausJakub** [comment]
Vlastní interpret by tímto měl být kompletní. 2ba10da9ac12b147f1d930ac440d0d0803e02e7d
