### ISSUE TITLE
Compiler statement

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#21]
Compiler pro jednotlivé statementy

- [x] compound

- [x] while do

- [x] do while

- [x] repeat until

- [x] for

- [x] if

- [x] switch

- [x] assignment

- [x] procedure

- [x] goto

- [x] ternary

- [x] I/O

**Comment by Kossyr** [comment]
switch bude zajímavý, podíváme se na to zítra

**Comment by SmausJakub** [comment]
Ano

**Comment by Kossyr** [comment]
case dodělán s 7fcd758ccf37b52dd7b930a2ab82582fc711dfa9
konečně zavírám
