### ISSUE TITLE
Změnit testovací soubory

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#27]
Testovací soubory by měly následovat jednotnou strukturu, tedy:

- testovací soubory pro compiler -> test_compiler_*.txt

- testovací soubory pro interpret -> test_interpret_*.txt

Měli bychom mít soubory se složitými programy, ale také jednoduché, kde se testuje nějaká jedna část programu, např. deklarace určitých typů, if statement apod.

**Comment by SmausJakub** [comment]
Souhlasím, dobrý nápad. Instrukce pro interpret si beru na starosti.

**Comment by SmausJakub** [comment]
Nebylo by lepší vytvořit dvě složky, jedna pro compiler a druhá pro interpret a tyto už nazývat podle toho, co mají provádět? Pozor na DRY. Stejně, pokud dojde k dalšímu dělení, tak se můžem zanořovat dál.

**Comment by Kossyr** [comment]
Zní to líp. Udělej pak commit pro interpret a já potom ten styl okopíruju pro překladač.

**Comment by SmausJakub** [comment]
Styl je navrhnut

**Comment by Kossyr** [comment]
bacha na názvy složek - heap - NEW,DEL,LDA,STA se bude blbě volat
to by bylo lepší mít název heap a pak ve složce readme.txt třeba s těmahle instrukcemi jestli je to třeba

**Comment by Kossyr** [comment]
Restrukturalizace provedena, tohle bych už zavřel
