### ISSUE TITLE
Chyby interpretu

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#28]
Jaké mohou nastat ? Budeme je strukturovat jako #26 ? Potom by mohly být #9  ?

**Comment by SmausJakub** [comment]
Bylo by hezké to mít použito i pro interpret. Nebudou ale zapotřebí další výpisy apod.? Errata kody se budou hodit, rozhodně s #9 souhlas.

**Comment by Kossyr** [comment]
No, udělali by se jenom další třídy v package errors a volal bys je přes error handler. Zatím je to bez jednotlivých kodu, ale to se dá napravit

**Comment by Kossyr** [comment]
Ale myslim že by to bylo dobrý.

**Comment by SmausJakub** [comment]
V to já také doufám.

**Comment by SmausJakub** [comment]
Chyby interpretu jsou nyní obsluhovány pomocí našeho errorHandleru. Uzavřeno
