### ISSUE TITLE
Doplnit základní gramatiku

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#3]
Je třeba ještě doplnit do základní gramatiky:

- [x]  - instrukce read a write
- [x] -  cyklus while do

**Comment by Kossyr** [comment]
- [x] negace proměnných

**Comment by SmausJakub** [comment]
Cyklus while do přidán do gramatiky.

**Comment by Kossyr** [comment]
Hotovo s ac2fad0c9e46d662b54400d55d369c9dc1b2d084
