### ISSUE TITLE
Goto a cykly

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#32]
V tuhle chvíli se dá skákat goto všude.

Otázkou je, jestli to nezakázat do cyklů. For cyklus by to položilo určitě, kdybychom skočili doprostřed bez inicializace.

Idee?

Z procedury do procedury to taky není dobrý, když se přeskočí inicializace proměnných.

**Comment by SmausJakub** [comment]
Zapřemýšlím se nad tím. Ty procedury jsou hloupost, to je zřejmé. Dokážem to zakázat do cyklů? Jestli jo, tak jsem pro

**Comment by Kossyr** [comment]
Do cyklů jsem si celkem jist jak to zakázat. U procedur by to mělo jít kontrolovat přes level. Vlastně to by už mělo fungovat, budu to muset vyzkoušet

**Comment by Kossyr** [comment]
Hm, tak funguje, že nejde skákat z vnitřku procedury ven.
Do procedury teď skákat jde.

**Comment by Kossyr** [comment]
While a repeat jsou v klidu př skocích, řekl bych že jediný for to prostě nerozdýchá. Takže tam bych to zakázal.

Co se týče těch procedur, tak bych to asi nechal na uživateli, že si dá při skákání do procedur pozor. Aspon zatim

**Comment by SmausJakub** [comment]
Vidím to stejně, teď jen dokázat zakázání foru.

**Comment by Kossyr** [comment]
zákaz skoku do for cyklu f7c3eec4fad2768f94b0ded0ac3a25d0440acfb9
