### ISSUE TITLE
Implicitní vs Explicitní přetypování

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#34]
Píšu to sem jako issue abych na to nezapomněl. V téhle chvíli není povoleno žádné přetypování. Ale nabízí se možnost povolit buď implicitní nebo explicitní. Nejdříve bych se ale soustředil na ostatní issue a tohle nechal na konci seznamu jako "hezké mít".

**Comment by Kossyr** [comment]
Půjdeme pro implicitní. Dam potom pár commitů, které to budou řešit v závislosti na něčem... to bude překvapení : )

**Comment by SmausJakub** [comment]
Takže to už není v seznamu hezké mít? Tak dobrá, vrhneme se na to :)

**Comment by Kossyr** [comment]
Mě se do toho původně nechtělo, protože by to bylo hodně práce ... což pořád sice platí, ale napadlo mi, jak to udělat, aby to bylo hezké.

Ale teď řeším jednu věc: 
Jak se chovat, když třeba máme if a < b, kde a je integer a b je real.
Protože výsledek toho bude boolean, tak nevim, podle čeho rozhodnout, jestli použijeme OPR nebo OPF.
Co myslíš ?

**Comment by Kossyr** [comment]
Zatím jsem tam dal OPR

**Comment by SmausJakub** [comment]
Kouknu na to, ale na to by nemělo jít použít ani jedno. Float číslo je uloženo na zásobníku v takovéto podobě: tento příklad je pro číslo 1.5 Takže toto není možné udělat. 
![obrazek](https://user-images.githubusercontent.com/15029725/34181864-3d40d736-e514-11e7-8c04-d492ff3b574c.png)

**Comment by Kossyr** [comment]
Jedno z nich na to musí jít použít. Programátorova chyba že je strká dohromady, ale my mu to rádi přetypujeme v default.

**Comment by Kossyr** [comment]
Co přetypovací instrukce?

**Comment by SmausJakub** [comment]
Ty samozřejmě existují, pravda, využijeme jich!

**Comment by Kossyr** [comment]
Takže, pokusil jsem se to vyřešit. Mějme tuhle deklaraci:
![image](https://user-images.githubusercontent.com/15073146/34205023-169f7db8-e581-11e7-86f8-8e2ce7ce6c10.png)
Takhle se to přeloží:
![image](https://user-images.githubusercontent.com/15073146/34205034-21bfd9f4-e581-11e7-9d7a-6e8e8844eecd.png)
řídí se to podle levé expression, takže ve chvíli kdy se načte ten real, tak se převede do integer a provede se součet

Když obrátíme:
![image](https://user-images.githubusercontent.com/15073146/34205057-3f62a32e-e581-11e7-8397-1d64fea1175d.png)
Tak přeloží:
![image](https://user-images.githubusercontent.com/15073146/34205066-4b44b0ec-e581-11e7-8c6b-6105fb26b7ec.png)
Jak je vidět, podle levé převede pravý integer na real, provede sečtení, potom zjistí, že dekalraujeme integer, a tak to převede na integer a až poté to uloží. 

Funguje pouze v default modu.

**Comment by SmausJakub** [comment]
Ano, souhlas. Takhle je to výborný!
