### ISSUE TITLE
Koncovky souborů

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#35]
Koncovky zdrojových souborů
a
Koncovky instrukčních souborů

Návrhy sem 🥇

**Comment by Kossyr** [comment]
pascal používá pas, takže to už nemužeme : (

napadlo mi pln, ale to už na netu taky existuje ...

**Comment by SmausJakub** [comment]
a pnl jakože pascalnullalike?

**Comment by Kossyr** [comment]
no nějak tak jsem to myslel. Bylo by to asi pro zdrojáky. Instrukční by tam třeba měly přidaný "i"

Takže .pln -> .ipln
ale pnl zní asi líp
 .pnl -> .ipnl

**Comment by Kossyr** [comment]
.pln a .ipln
