### ISSUE TITLE
Příprava na kodování

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#4]
Vytvořit:

- [x] pdf s gramatikou @Kossyr

- [x] pdf se symboly a klíčovými slovy @SmausJakub 

- [x] pdf s errata kody @Kossyr

- [x] pdf s instrukční sadou @SmausJakub

**Comment by Kossyr** [comment]
Errata kody aspon promyslet, ted stejne asi nebudeme vedet vsechny

**Comment by SmausJakub** [comment]
Symboly a klíčový slova a rovněž instrukční sada přidána

**Comment by SmausJakub** [comment]
hotovo s 81c5e2ae0f2651410f32087b3a05bd3d5ca81a10
