### ISSUE TITLE
Aktualizovat pdf

### ISSUE THREAD

**Issue by Kossyr** [SmausJakub/heine-fluch#9]
Je třeba aktualizovat pdf, především symboly a klíčová slova

**Comment by Kossyr** [comment]
Jak to vypadá? : )

**Comment by SmausJakub** [comment]
Na všem se pracuje, dnes bude velký commit : )

**Comment by Kossyr** [comment]
Vzhledem k tomu, že to dělá ANTLR, tak nebudeme potřebovat pdf Symboly a klicova slova...

Minimálně se to ale může hodit na rychlé kouknutí na klíčová slova : )

**Comment by SmausJakub** [comment]
Navrhuji přeměnit některé soubory do latexu, ve kterém bude napsaná dokumentace, aby je bylo možné rovnou použít pomocí zdrojového kódu.

**Comment by Kossyr** [comment]
To je dost dobrý nápad. Mohl bys udělat základní zdroják na to ? A klidně bych to hodil na github rovnou.
Připravil bys mi tex na tui tabulku s chybami analýzy ? Teď na tom pracuju a potřeboval bych je zapsat.

**Comment by SmausJakub** [comment]
Základní zdroják vypracován, rovněž hozen na git. V texu je takový nástřel pro tabulku, chceme i separátní dokumenty pro ty PDF?

**Comment by Kossyr** [comment]
Spíš jsem si říkal, že bychom měli separátní takhle v Tex... a pak to jenom házeli do toho hlavního

**Comment by Kossyr** [comment]
zbývá doplnit ty chybové výpisy. možná i ty klíčová slova by možná daly, ale muselo by se to předělat bez těch symbolů

**Comment by Kossyr** [comment]
Tabulky jsou v dokumentaci, hotovo
